spring:
  datasource:
    username: root
    password: Messirve12345*
    url: jdbc:mysql://127.0.0.1:3306/prueba
  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher